pcm.reliefos_mix {
    type dmix
    ipc_key 1380273241
    ipc_key_add_uid true
    ipc_perm 0600
 slave { pcm "hw:0,0" rate 48000 format S16_LE channels 2 period_size 8192 buffer_size 65536 }
}
pcm.reliefos_record {
    type dsnoop
    ipc_key 1380273242
    ipc_key_add_uid true
    ipc_perm 0600
 slave { pcm "hw:0,0" rate 48000 format S16_LE channels 2 period_size 8192 buffer_size 65536 }
}
pcm.!default {
    type asym
    playback.pcm { type plug slave.pcm "reliefos_mix" }
    capture.pcm { type plug slave.pcm "reliefos_record" }
}
ctl.!default { type hw card 0 }
