/* Transitional compatibility forwarder (ReliefOS / ReliefNT rename).
 * Canonical declarations: <reliefos/blockdev.h>.
 * No second layout definition exists behind these names. */
#ifndef LEONOS_BLOCKDEV_H
#define LEONOS_BLOCKDEV_H
#include <reliefos/blockdev.h>

/* Old names alias the single canonical declaration. */
#define LEONOS_BLOCK_FILESYSTEM_EXFAT RELIEFOS_BLOCK_FILESYSTEM_EXFAT
#define LEONOS_BLOCK_FILESYSTEM_EXT2 RELIEFOS_BLOCK_FILESYSTEM_EXT2
#define LEONOS_BLOCK_FILESYSTEM_EXT4 RELIEFOS_BLOCK_FILESYSTEM_EXT4
#define LEONOS_BLOCK_FILESYSTEM_FAT32 RELIEFOS_BLOCK_FILESYSTEM_FAT32
#define LEONOS_BLOCK_FILESYSTEM_ISO9660 RELIEFOS_BLOCK_FILESYSTEM_ISO9660
#define LEONOS_BLOCK_FILESYSTEM_UNKNOWN RELIEFOS_BLOCK_FILESYSTEM_UNKNOWN
#define LEONOS_BLOCK_GPT_BASIC_DATA RELIEFOS_BLOCK_GPT_BASIC_DATA
#define LEONOS_BLOCK_GPT_ESP RELIEFOS_BLOCK_GPT_ESP
#define LEONOS_BLOCK_GPT_LINUX RELIEFOS_BLOCK_GPT_LINUX
#define LEONOS_BLOCK_MAX_DISKS RELIEFOS_BLOCK_MAX_DISKS
#define LEONOS_BLOCK_MAX_PARTITIONS RELIEFOS_BLOCK_MAX_PARTITIONS
#define LEONOS_BLOCK_NAME_LEN RELIEFOS_BLOCK_NAME_LEN
#define LEONOS_BLOCK_PATH_LEN RELIEFOS_BLOCK_PATH_LEN
#define leonos_block_disk_info reliefos_block_disk_info
#define leonos_block_filesystem reliefos_block_filesystem
#define leonos_block_filesystem_name reliefos_block_filesystem_name
#define leonos_block_format reliefos_block_format
#define leonos_block_get_info reliefos_block_get_info
#define leonos_block_gpt_create reliefos_block_gpt_create
#define leonos_block_gpt_delete reliefos_block_gpt_delete
#define leonos_block_gpt_initialize reliefos_block_gpt_initialize
#define leonos_block_gpt_set_name reliefos_block_gpt_set_name
#define leonos_block_gpt_resize reliefos_block_gpt_resize
#define leonos_block_gpt_set_type reliefos_block_gpt_set_type
#define leonos_block_gpt_type reliefos_block_gpt_type
#define leonos_block_gpt_type_name reliefos_block_gpt_type_name
#define leonos_block_list_disks reliefos_block_list_disks
#define leonos_block_list_partitions reliefos_block_list_partitions
#define leonos_block_partition reliefos_block_partition
#define leonos_block_partition_path reliefos_block_partition_path
#define leonos_block_partition_uuid reliefos_block_partition_uuid
#define leonos_block_probe_filesystem reliefos_block_probe_filesystem
#endif /* LEONOS_BLOCKDEV_H */
